services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - client/.env
    environment:
      - VITE_SERVER_URL=https://salmanayazz-server--3001.prod1.defang.dev
    domainname: www.interviewprep.study
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - server/.env
    environment:
      - CLIENT_URL=https://www.interviewprep.study
